### PR TITLE
Use temporary folders for parallel results; configure NetLogo extensions folder.

### PR DESCRIPTION
**Pull request by tfrench**
The `hash` approach didn't work well for me. Using temporary folders is a safer approach.

### CODE REVIEW

**Comment by tfrench** [comment]
Yes, sure. 

There are now two changes: 

1. I had issues using hash id of the object when running parallel simulations. It's safer to use a temporary dir.

2. Since we are not running NetLogo from it's home directory, we configure the extensions folder. It should fix #13.

Thanks.

**Comment by quaquel** [comment]
Ok, great. I will merge this as soon as possible. 

Your fix for #13 is for mac or linux right? I will check the folder on windows to make sure it works there as well.

thanks again

**Comment by tfrench** [comment]
Yes, it's for OSX and Linux (system we use). I don't have a Windows box to try it on; sorry about that.

**Comment by quaquel** [comment]
Don't worry, I have windows through parallels on a mac and can add it quite easily.

**Pull request merged**
